export const PLUGIN_SOURCE = `// grappling_hook.js — generated by ModForge ForgeCore v3.1
// model: index.grappling_hook.bbmodel · seed 0x7F3A91 · non-blocking
import { Server, world, system } from "@minecraft/server";

const ENERGY_COST = 5;
const PULL_SPEED = 1.8;
const OVERWORLD = world.getDimension("overworld");
const Energy = new Map(); // playerId -> cosmic energy bar

Server.beforeEvents.itemUse.subscribe(({ source, itemStack }) => {
  if (itemStack?.typeId !== "modforge:grappling_hook") return;

  if ((Energy.get(source.id) ?? 100) < ENERGY_COST) {
    source.playSound("ui.deny");
    return; // insufficient cosmic charge
  }
  Energy.set(source.id, (Energy.get(source.id) ?? 100) - ENERGY_COST);

  const target = source.getBlockFromViewDirection({ maxDistance: 32 });
  if (!target) return;

  emitBurst(source.location, "minecraft:portal_particle");
  latch(source, target, PULL_SPEED);
  emitBurst(target.location, "minecraft:enchanting_table_particle");
});

function latch(actor, block, speed) {
  const delta = block.location.subtract(actor.location);
  const steps = Math.max(4, Math.floor(delta.length() / speed));
  let step = 0;

  const pulse = system.runInterval(() => {
    step += 1;
    const t = step / steps;
    const eased = 1 - Math.pow(1 - t, 3); // easeOutCubic
    actor.teleport(
      actor.location.add(delta.multiply(eased)),
      { dimension: actor.dimension }
    );
    if (step >= steps) system.clearRun(pulse);
  }, 2);
}

function emitBurst(location, particleId) {
  OVERWORLD.spawnParticle(particleId, location.add({ x: 0, y: 1, z: 0 }));
}
`;

export const PROMPT_DEFAULT =
  "Write a server script for a custom grappling hook item. When a player right-clicks, fire a vector-based velocity line toward the target block, pull the player smoothly to that location, trigger particle clouds at both origin and destination, and deduct 5 energy points from their custom player data map.";

export const VOXEL_PROMPT_DEFAULT =
  "A sleek, modern steampunk grappling hook device forged from brass and glowing ender quartz crystals.";